/*
  Warnings:

  - The values [LOGIN_SUCCESS,LOGIN_FAILED,TOKEN_REFRESH,FORBIDDEN_PLAN_ACCESS] on the enum `logs_action` will be removed. If these variants are still used in the database, this will fail.

*/
-- AlterTable
ALTER TABLE `logs` MODIFY `action` ENUM('LOGIN', 'LOGOUT', 'REFRESH_TOKEN', 'CHANGE_PASSWORD', 'PASSWORD_RESET_REQUEST', 'PASSWORD_RESET_COMPLETE', 'FORBIDDEN_MOBILE_LOGIN', 'UNAUTHORIZED_ACCESS', 'PLAN_VIOLATION', 'TOKEN_EXPIRED', 'TOKEN_REVOKED', 'INVALID_CREDENTIALS', 'CREATE_USER', 'UPDATE_USER', 'DELETE_USER', 'ACTIVATE_USER', 'DEACTIVATE_USER', 'CREATE_CUSTOMER', 'UPDATE_CUSTOMER', 'DELETE_CUSTOMER', 'VIEW_CUSTOMER', 'CREATE_APPOINTMENT', 'UPDATE_APPOINTMENT', 'CANCEL_APPOINTMENT', 'COMPLETE_APPOINTMENT', 'MISS_APPOINTMENT', 'VIEW_APPOINTMENT', 'CREATE_DEVICE', 'UPDATE_DEVICE', 'DELETE_DEVICE', 'CREATE_PAYMENT', 'UPDATE_PAYMENT', 'DELETE_PAYMENT', 'REFUND_PAYMENT', 'VIEW_REPORT', 'EXPORT_REPORT', 'CHANGE_PLAN', 'UPDATE_SETTINGS', 'SYSTEM_ERROR') NOT NULL;
